### ISSUE TITLE
Inquiry of item_idx_mapping   for the items in user_item_pretrain.csv

### ISSUE THREAD

**Issue by zyrmj0212** [BundleRec/bundle_recommendation#2]
Hi, really appreciate your contribution for this new dataset. I want to supplement some side informations from original amazon dataset about the items in the user_item_pretrain file. However, I cannot recover the original item idx based on the provided item_idx_mapping file for the items that not appered in the collected bundle are not included in this index file. So, could you please provide a complete version of the item index file which include all the items you collected in the dataset?

**Comment by hoangpanda** [comment]
same problem, where can I contact you to discuss this?

**Comment by zyrmj0212** [comment]
> same problem, where can I contact you to discuss this?

My current solution is to construct my own user-item interaction history for pre-train based on the original Amazon dataset.
you can found the dataset on https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2/. And I'm happy to discuss more with you if you have better idea or any other questions. Here is my email address: yurouzhao2021@gmail.com

**Comment by BundleRec** [comment]
Thank you for your attention to our project. I've updated the comprehensive item source index ([item_idx_mapping.csv](https://github.com/BundleRec/bundle_recommendation/tree/main/dataset/electronic)) within our dataset for your reference. Additionally, it's important to note that we utilize the Amazon Reviews dataset from [2014](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html). As such, some products mentioned may not be present in subsequent versions of the dataset, such as the Amazon Reviews 2018. Please keep this in mind when cross-referencing or looking for specific products.
